### PR TITLE
Add the means to retrieve token file from disk as cache fallback (if not found on default cache)

### PR DESCRIPTION
**Pull request by ardumont**
Hello,

Just a proposal.

I used a script command before that did the upload.
It does not work at the moment.

But this package does.
There is a slight workflow difference with my own.
I load the token from disk.

This script just loaded the token file ~/.marmalade/token and provided
it to curl as an option.

For deploying my latest package, I tricked marmalade-upload `(puthash "ardumont"
my-token marmalade/tokens)`.

So I just extracted a function that retrieved the token.
If first tries as originally from the cache.
If nothing is found, try to load the `~/.marmalade/<username>` if the file exists.
If it does, it loads its content (which is assumed to be exactly the
token).
If nothing is found, returns nil.

This function is used at 2 positions:
- when computing the arguments to determine if the password is needed or not
- in the lambda when doing the actual upload request

As I do not know if you are interested at all, I did not:
- adapt the removal steps when the token is invalid (the token file could be removed?)
- nor update the cache with the token file's content (the token file's content can be poured into the cache?)

Cheers,

### CODE REVIEW

**Comment by nicferrier** [comment]
I like it. Two things:
- could you add a custom var so we can abstract the name of the token file? is that sensible?
- the second patch isn't necessary, marmalade-upload uses / as the namespace separator, not /--

I'll happily pull this if you drop the 2nd thing even if you don't do the first.

**Comment by ardumont** [comment]
Hello,

> I like it.

Cool.

> could you add a custom var so we can abstract the name of the token file? 

Ok. 
To ensure I understood, not everyone will use its login as token filename so I sandbox this in a defcustom or defvar, is that it?

> is that sensible?

Not at all. I, for one, use `~/.marmalade/token` not `~/.marmalade/ardumont`, I changed for this proposal.

> the second patch isn't necessary, marmalade-upload uses / as the namespace separator, not /--

Ok, I can rename no problem.

> I'll happily pull this if you drop the 2nd thing even if you don't do the first.

I'll do both :D

Cheers,

**Comment by ardumont** [comment]
Is that ok?

Here are the use cases I see:
- use case 1: the user ardumont sets to default, so this will look for ~/.marmalade/ardumont as the token file

``` lisp
(setq marmalade/default-token-name)
(marmalade/compute-token-filepath "ardumont")
```

Renders /home/tony/.marmalade/ardumont
- use case 2: the user ardumont sets to token, so this will look for ~/.marmalade/token as the token file

``` lisp
(setq marmalade/default-token-name "token")
(marmalade/compute-token-filepath "ardumont")
```

Renders /home/tony/.marmalade/token

**Comment by nicferrier** [comment]
Those aren't defcustoms of course but they'll do for now!

Looks like we're all done to me.

**Comment by ardumont** [comment]
> Those aren't defcustoms of course but they'll do for now!

Yes, I do not know them yet but I do see lots of people using them.
I can learn and push you another PR, what do you think?

Nic Ferrier writes:

> Those aren't defcustoms of course but they'll do for now!
> 
> Looks like we're all done to me.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/nicferrier/emacs-marmalade-upload/pull/1#issuecomment-46031450

## 

@ardumont

**Comment by nicferrier** [comment]
it's not necessary... I'll get them done at some point.

Of course, it's nice to get patches!

**Pull request merged**
